### ISSUE TITLE
The system is down!

### ISSUE THREAD

**Issue by greypants** [bw-vbnm/bw-vbnm.github.io#3]
Just a heads up, your personal site is **404'd!** . 

![image](https://cloud.githubusercontent.com/assets/647549/14784448/c608b6ec-0ac3-11e6-8be7-4090770f7cf2.png)

Your gh-pages branch should just contain the contents of `dist`, so that `index.html` is at the root. If you're using gulp (looks like you are on another branch), you can use [gulp-gh-pages](https://www.npmjs.com/package/gulp-gh-pages) to specify a directory (dist) to deploy to GitHub pages from any branch.

**Comment by bw-vbnm** [comment]
Hi, thanks for the issue, I've been redesigning my site and I haven't gotten around to putting up a placeholder site just yet.
